#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v10
# autospec commit: 6fa3d52
#
Name     : mangohud
Version  : 0.7.2
Release  : 2
URL      : https://github.com/flightlessmango/MangoHud/releases/download/v0.7.2/MangoHud-v0.7.2-Source.tar.xz
Source0  : https://github.com/flightlessmango/MangoHud/releases/download/v0.7.2/MangoHud-v0.7.2-Source.tar.xz
Summary  : A Vulkan and OpenGL overlay for monitoring FPS, temperatures, CPU/GPU load and more.
Group    : Development/Tools
License  : Apache-2.0
Requires: mangohud-bin = %{version}-%{release}
Requires: mangohud-data = %{version}-%{release}
Requires: mangohud-lib = %{version}-%{release}
Requires: mangohud-man = %{version}-%{release}
BuildRequires : appstream-bin
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : gcc-staticdev
BuildRequires : glslang-bin
BuildRequires : libglvnd-dev
BuildRequires : libxkbcommon-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(glew)
BuildRequires : pkgconfig(glfw3)
BuildRequires : pkgconfig(spdlog)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pypi-mako
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# MangoHud
A Vulkan and OpenGL overlay for monitoring FPS, temperatures, CPU/GPU load and more.

%package bin
Summary: bin components for the mangohud package.
Group: Binaries
Requires: mangohud-data = %{version}-%{release}

%description bin
bin components for the mangohud package.


%package data
Summary: data components for the mangohud package.
Group: Data

%description data
data components for the mangohud package.


%package doc
Summary: doc components for the mangohud package.
Group: Documentation
Requires: mangohud-man = %{version}-%{release}

%description doc
doc components for the mangohud package.


%package lib
Summary: lib components for the mangohud package.
Group: Libraries
Requires: mangohud-data = %{version}-%{release}

%description lib
lib components for the mangohud package.


%package man
Summary: man components for the mangohud package.
Group: Default

%description man
man components for the mangohud package.


%prep
%setup -q -n MangoHud-v0.7.2
cd %{_builddir}/MangoHud-v0.7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716785956
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dmangoapp=true \
-Dmangoapp_layer=true \
-Dmangohudctl=true \
-Dinclude_doc=true \
-Duse_system_spdlog=enabled \
-Dwith_wayland=enabled \
-Dwith_xnvctrl=disabled  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mangoapp
/usr/bin/mangohud
/usr/bin/mangohudctl
/usr/bin/mangoplot

%files data
%defattr(-,root,root,-)
/usr/share/icons/hicolor/scalable/apps/io.github.flightlessmango.mangohud.svg
/usr/share/metainfo/io.github.flightlessmango.mangohud.metainfo.xml
/usr/share/vulkan/implicit_layer.d/MangoHud.x86_64.json
/usr/share/vulkan/implicit_layer.d/libMangoApp.x86_64.json

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/mangohud/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/mangohud/libMangoApp.so
/usr/lib64/mangohud/libMangoHud.so
/usr/lib64/mangohud/libMangoHud_dlsym.so
/usr/lib64/mangohud/libMangoHud_opengl.so

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mangoapp.1
/usr/share/man/man1/mangohud.1
